import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { jaJP } from "@clerk/localizations";
import { Provider } from "@/components/ui/provider"
import { Header } from "@/components/ui/molecules/Header";
import { Footer } from "@/components/ui/molecules/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aisty:ECショッピングでも試着を",
  description: "Generated by create next app",
};

// jaJP の中身をスプレッドしてコピーし、必要な箇所だけ上書き
const customJaJP = {
  ...jaJP,
  signIn: {
    ...jaJP.signIn,

  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={customJaJP}>
      <html suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Provider>
            <Header />
            {children}
            <Footer />
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
